[package]
name = "ricat"
version = "0.4.3"
edition = "2021"
authors = ["Aditya Navphule <adityanav@duck.com>"]
description = "A Rust-Based implemenation of classic UNIX `cat` command"
repository = "https://github.com/adityanav123/ricat"
license = "MIT"
keywords = ["cat", "cli", "text-processing", "file", "system-tools"]
documentation = "https://adityanav123.github.io/ricat"
build = "build.rs"

[[bin]]
name = "ricat"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.2", features = ["derive"]}
regex = "1.10.3"
crossterm = "0.27.0"
base64 = "0.22.0"
thiserror = "1.0.59"
criterion = "0.5.1"
memmap2 = "0.9.4"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
toml = "0.8.13"
dirs = "5.0.1"

[build-dependencies]
dirs = "5.0.1"
